In [202]:
import pandas as pd
import numpy as np
import re
pd.set_option('Display.max_rows', 1000)

In [179]:
df = pd.read_csv('zomato_restaurants_lisbon')
df.drop('ID', inplace=True, axis=1)
df

,name,neighborhood,avg_rating,#_of_ratings,avg_cost,cash_cards?,type,cuisine,more_infos
0,Geladaria Freddo,Corroios,3.6,27,8 € for two people (approx.),Cash and Cards accepted,['Ice-cream Shop'],"['Ice Cream', 'Corroios']","['Breakfast', 'Full Bar Available', 'Indoor Se..."
1,Restaurante Baía,Cascais Centro,3.8,24,50 € for two people (approx.),Debit Cards accepted,['Fine Dining'],"['Portuguese', 'Cascais Centro']","['Full Bar Available', 'Kid Friendly', 'Group ..."
2,Menos Um,Venteira,2.9,66,20 € for two people (approx.),Debit Cards accepted,['Casual Dining'],"['Burger', 'Venteira']","['Takeaway Available', 'Full Bar Available', '..."
3,Real Cake,Loures Centro,2.8,61,15 € for two people (approx.),Debit Cards accepted,['Snack Bar'],"['Finger Food', 'Loures Centro']","['Breakfast', 'Takeaway Available', 'Full Bar ..."
4,Bolos Caseiros,Penha de França,3.5,7,15 € for two people (approx.),Cash only,['Snack Bar'],"['Finger Food', 'Portuguese', 'Penha de França']","['Takeaway Available', 'Full Bar Available', '..."
...,...,...,...,...,...,...,...,...,...
12415,Inevitável - Vila Galé Collection Palácio dos ...,Paço de Arcos,4.1,37,100 € for two people (approx.),Cash and Cards accepted,['Fine Dining'],"['Portuguese', 'Mediterranean', 'Italian', 'Pa...","['Full Bar Available', 'Outdoor Seating', 'Wif..."
12416,Flor de Lis - EPIC SANA Lisboa Hotel,Rato,4.4,98,100 € for two people (approx.),Cash and Cards accepted,['Fine Dining'],"['Author', 'Mediterranean', 'Portuguese', 'Rato']","['Breakfast', 'Full Bar Available', 'Brunch', ..."
12417,Midori - Penha Longa Resort,Alcabideche,4.6,246,220 € for two people (approx.),Cash and Cards accepted,['Fine Dining'],"['Japanese', 'Sushi', 'Author', 'Alcabideche']","['Full Bar Available', 'Indoor Seating', 'Luxu..."
12418,Tágide,Chiado,4.2,235,65 € for two people (approx.),Cash and Cards accepted,['Fine Dining'],"['Portuguese', 'Chiado']","['Full Bar Available', 'Lunch Menu', 'River Vi..."
12419,A Confraria - York House Lisboa Hotel,Santos,3.7,12,50 € for two people (approx.),Cash and Cards accepted,['Fine Dining'],"['Portuguese', 'Tea', 'Santos']","['Breakfast', 'Full Bar Available', 'Rooftop',..."

In [180]:
df[df['cash_cards?'] == "How do we calculate cost for two?"]

,name,neighborhood,avg_rating,#_of_ratings,avg_cost,cash_cards?,type,cuisine,more_infos
1295,Rosa Café,Linda-a-Velha,-,0,6 € for two people (approx.),How do we calculate cost for two?,['Snack Bar'],"['Cafe', 'Finger Food', 'Linda-a-Velha']","['Breakfast', 'Takeaway Available', 'Full Bar ..."
2401,Café da Mila,São João,3.0,2,8 € for two people (approx.),How do we calculate cost for two?,['Snack Bar'],"['Cafe', 'Finger Food', 'São João']","['Breakfast', 'Full Bar Available', 'Sports TV..."
3652,Cafetaria da Parada,São João,3.2,0,6 € for two people (approx.),How do we calculate cost for two?,['Snack Bar'],"['Cafe', 'Bakery', 'São João']","['Breakfast', 'Full Bar Available', 'Indoor Se..."

In [181]:
# Create a column with a numerical value for avg_cost
avg_cost = df['avg_cost']
avg_cost
df['avg_cost_2'] = [int(re.match('\d+', string).group()) for string in avg_cost]

In [182]:
df

,name,neighborhood,avg_rating,#_of_ratings,avg_cost,cash_cards?,type,cuisine,more_infos,avg_cost_2
0,Geladaria Freddo,Corroios,3.6,27,8 € for two people (approx.),Cash and Cards accepted,['Ice-cream Shop'],"['Ice Cream', 'Corroios']","['Breakfast', 'Full Bar Available', 'Indoor Se...",8
1,Restaurante Baía,Cascais Centro,3.8,24,50 € for two people (approx.),Debit Cards accepted,['Fine Dining'],"['Portuguese', 'Cascais Centro']","['Full Bar Available', 'Kid Friendly', 'Group ...",50
2,Menos Um,Venteira,2.9,66,20 € for two people (approx.),Debit Cards accepted,['Casual Dining'],"['Burger', 'Venteira']","['Takeaway Available', 'Full Bar Available', '...",20
3,Real Cake,Loures Centro,2.8,61,15 € for two people (approx.),Debit Cards accepted,['Snack Bar'],"['Finger Food', 'Loures Centro']","['Breakfast', 'Takeaway Available', 'Full Bar ...",15
4,Bolos Caseiros,Penha de França,3.5,7,15 € for two people (approx.),Cash only,['Snack Bar'],"['Finger Food', 'Portuguese', 'Penha de França']","['Takeaway Available', 'Full Bar Available', '...",15
...,...,...,...,...,...,...,...,...,...,...
12415,Inevitável - Vila Galé Collection Palácio dos ...,Paço de Arcos,4.1,37,100 € for two people (approx.),Cash and Cards accepted,['Fine Dining'],"['Portuguese', 'Mediterranean', 'Italian', 'Pa...","['Full Bar Available', 'Outdoor Seating', 'Wif...",100
12416,Flor de Lis - EPIC SANA Lisboa Hotel,Rato,4.4,98,100 € for two people (approx.),Cash and Cards accepted,['Fine Dining'],"['Author', 'Mediterranean', 'Portuguese', 'Rato']","['Breakfast', 'Full Bar Available', 'Brunch', ...",100
12417,Midori - Penha Longa Resort,Alcabideche,4.6,246,220 € for two people (approx.),Cash and Cards accepted,['Fine Dining'],"['Japanese', 'Sushi', 'Author', 'Alcabideche']","['Full Bar Available', 'Indoor Seating', 'Luxu...",220
12418,Tágide,Chiado,4.2,235,65 € for two people (approx.),Cash and Cards accepted,['Fine Dining'],"['Portuguese', 'Chiado']","['Full Bar Available', 'Lunch Menu', 'River Vi...",65
12419,A Confraria - York House Lisboa Hotel,Santos,3.7,12,50 € for two people (approx.),Cash and Cards accepted,['Fine Dining'],"['Portuguese', 'Tea', 'Santos']","['Breakfast', 'Full Bar Available', 'Rooftop',...",50

In [183]:
for index, value in df['type'].iteritems():
    df.loc[index, 'type'] = value.replace("[", '').replace("]", '').replace("'", '')
for index, value in df['cuisine'].iteritems():
    df.loc[index, 'cuisine'] = value.replace("[", '').replace("]", '').replace("'", '')
for index, value in df['more_infos'].iteritems():
    df.loc[index, 'more_infos'] = value.replace("[", '').replace("]", '').replace("'", '')

In [184]:
types = [value.split(', ') for value in df['type']]
df_types = df.loc[:, ['name', 'neighborhood', 'avg_rating', '#_of_ratings', 'avg_cost', 'avg_cost_2', 'cash_cards?']]
df_types['type1'] = [value[0] for value in types]
df_types['type2'] = [value[1] if len(value) > 1 else '' for value in types]

In [185]:
df_types = pd.melt(df_types, id_vars=['name', 'neighborhood', 'avg_rating', '#_of_ratings', 'avg_cost', 'avg_cost_2', 'cash_cards?'])

In [186]:
df_types.drop(df_types[(df_types['value'] == '') & (df_types['variable'] == 'type2')].index, inplace=True)
df_types

,name,neighborhood,avg_rating,#_of_ratings,avg_cost,avg_cost_2,cash_cards?,variable,value
0,Geladaria Freddo,Corroios,3.6,27,8 € for two people (approx.),8,Cash and Cards accepted,type1,Ice-cream Shop
1,Restaurante Baía,Cascais Centro,3.8,24,50 € for two people (approx.),50,Debit Cards accepted,type1,Fine Dining
2,Menos Um,Venteira,2.9,66,20 € for two people (approx.),20,Debit Cards accepted,type1,Casual Dining
3,Real Cake,Loures Centro,2.8,61,15 € for two people (approx.),15,Debit Cards accepted,type1,Snack Bar
4,Bolos Caseiros,Penha de França,3.5,7,15 € for two people (approx.),15,Cash only,type1,Snack Bar
...,...,...,...,...,...,...,...,...,...
24763,Fonte dos Arcos,Oeiras e São Julião da Barra,-,0,7 € for two people (approx.),7,Cash and Debit Cards accepted,type2,Snack Bar
24764,Via Láctea,São Brás,3.7,16,30 € for two people (approx.),30,Cash and Debit Cards accepted,type2,Bar
24773,Sacramento,Chiado,4.5,794,50 € for two people (approx.),50,Cash and Cards accepted,type2,Bar
24785,Gambrinus,Rossio,4.6,388,110 € for two people (approx.),110,Cash and Cards accepted,type2,Bar
24787,Ipsylon - The Oitavos Hotel,Guincho,3.9,32,80 € for two people (approx.),80,Cash and Cards accepted,type2,Bar

In [190]:
# Create a list with all the cuisines per restaurant and drop the last value for each sublist (erroneously imported the neighborhood name)
cuisines_list = [value.split(', ') for value in df['cuisine']]
for cuisines in cuisines_list:
    del cuisines[-1]

8

In [193]:
df_cuisines = df.loc[:, ['name', 'neighborhood', 'avg_rating', '#_of_ratings', 'avg_cost', 'avg_cost_2', 'cash_cards?']]
for j in range(0, len(cuisines_list)):
    cuisines = cuisines_list[j]
    for i in range(0, len(cuisines)):
        df_cuisines.loc[j, 'cuisine' + str(i+1)] = cuisines[i]
df_cuisines

,name,neighborhood,avg_rating,#_of_ratings,avg_cost,avg_cost_2,cash_cards?,cuisine1,cuisine2,cuisine3,cuisine4,cuisine5,cuisine6,cuisine7,cuisine8
0,Geladaria Freddo,Corroios,3.6,27,8 € for two people (approx.),8,Cash and Cards accepted,Ice Cream,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Restaurante Baía,Cascais Centro,3.8,24,50 € for two people (approx.),50,Debit Cards accepted,Portuguese,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Menos Um,Venteira,2.9,66,20 € for two people (approx.),20,Debit Cards accepted,Burger,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Real Cake,Loures Centro,2.8,61,15 € for two people (approx.),15,Debit Cards accepted,Finger Food,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bolos Caseiros,Penha de França,3.5,7,15 € for two people (approx.),15,Cash only,Finger Food,Portuguese,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12415,Inevitável - Vila Galé Collection Palácio dos ...,Paço de Arcos,4.1,37,100 € for two people (approx.),100,Cash and Cards accepted,Portuguese,Mediterranean,Italian,NaN,NaN,NaN,NaN,NaN
12416,Flor de Lis - EPIC SANA Lisboa Hotel,Rato,4.4,98,100 € for two people (approx.),100,Cash and Cards accepted,Author,Mediterranean,Portuguese,NaN,NaN,NaN,NaN,NaN
12417,Midori - Penha Longa Resort,Alcabideche,4.6,246,220 € for two people (approx.),220,Cash and Cards accepted,Japanese,Sushi,Author,NaN,NaN,NaN,NaN,NaN
12418,Tágide,Chiado,4.2,235,65 € for two people (approx.),65,Cash and Cards accepted,Portuguese,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12419,A Confraria - York House Lisboa Hotel,Santos,3.7,12,50 € for two people (approx.),50,Cash and Cards accepted,Portuguese,Tea,NaN,NaN,NaN,NaN,NaN,NaN

In [194]:
# Melt the various cuisine columns
df_cuisines = pd.melt(df_cuisines, id_vars=['name', 'neighborhood', 'avg_rating', '#_of_ratings', 'avg_cost', 'avg_cost_2', 'cash_cards?'])

In [203]:
# Drop the rows with Nan values
df_cuisines.drop(df_cuisines[(df_cuisines['value'].isnull()) & (df_cuisines['variable'] != 'cuisine1')].index, inplace=True)
df_cuisines

,name,neighborhood,avg_rating,#_of_ratings,avg_cost,avg_cost_2,cash_cards?,variable,value
0,Geladaria Freddo,Corroios,3.6,27,8 € for two people (approx.),8,Cash and Cards accepted,cuisine1,Ice Cream
1,Restaurante Baía,Cascais Centro,3.8,24,50 € for two people (approx.),50,Debit Cards accepted,cuisine1,Portuguese
2,Menos Um,Venteira,2.9,66,20 € for two people (approx.),20,Debit Cards accepted,cuisine1,Burger
3,Real Cake,Loures Centro,2.8,61,15 € for two people (approx.),15,Debit Cards accepted,cuisine1,Finger Food
4,Bolos Caseiros,Penha de França,3.5,7,15 € for two people (approx.),15,Cash only,cuisine1,Finger Food
...,...,...,...,...,...,...,...,...,...
86794,ŌKAH Restaurant & Rooftop,Santos,4.3,200,60 € for two people (approx.),60,Cash and Cards accepted,cuisine7,Middle Eastern
90723,Granier,Campo Pequeno,3.7,125,10 € for two people (approx.),10,Cash and Debit Cards accepted,cuisine8,Sandwich
91565,Galaxy kebab and pizza house,Brandoa,-,1,16 € for two people (approx.),16,Cash only,cuisine8,Vegetarian
97365,Coffeetaria,Barreiro Centro,4.3,231,15 € for two people (approx.),15,Cash and Debit Cards accepted,cuisine8,Crepes
99208,Food Mercearia Biológica,Santos,3.1,38,15 € for two people (approx.),15,Cash and Debit Cards accepted,cuisine8,Juices