In [5]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv('zomato_restaurants_lisbon', index_col='ID')
df

,name,neighborhood,avg_rating,#_of_ratings,avg_cost,cash_cards?,type,cuisine,more_infos
ID,,,,,,,,,
0,Geladaria Freddo,Corroios,3.6,27,8 € for two people (approx.),Cash and Cards accepted,['Ice-cream Shop'],"['Ice Cream', 'Corroios']","['Breakfast', 'Full Bar Available', 'Indoor Se..."
1,Restaurante Baía,Cascais Centro,3.8,24,50 € for two people (approx.),Debit Cards accepted,['Fine Dining'],"['Portuguese', 'Cascais Centro']","['Full Bar Available', 'Kid Friendly', 'Group ..."
2,Menos Um,Venteira,2.9,66,20 € for two people (approx.),Debit Cards accepted,['Casual Dining'],"['Burger', 'Venteira']","['Takeaway Available', 'Full Bar Available', '..."
3,Real Cake,Loures Centro,2.8,61,15 € for two people (approx.),Debit Cards accepted,['Snack Bar'],"['Finger Food', 'Loures Centro']","['Breakfast', 'Takeaway Available', 'Full Bar ..."
4,Bolos Caseiros,Penha de França,3.5,7,15 € for two people (approx.),Cash only,['Snack Bar'],"['Finger Food', 'Portuguese', 'Penha de França']","['Takeaway Available', 'Full Bar Available', '..."
...,...,...,...,...,...,...,...,...,...
12672,Inevitável - Vila Galé Collection Palácio dos ...,Paço de Arcos,4.1,37,100 € for two people (approx.),Cash and Cards accepted,['Fine Dining'],"['Portuguese', 'Mediterranean', 'Italian', 'Pa...","['Full Bar Available', 'Outdoor Seating', 'Wif..."
12673,Flor de Lis - EPIC SANA Lisboa Hotel,Rato,4.4,98,100 € for two people (approx.),Cash and Cards accepted,['Fine Dining'],"['Author', 'Mediterranean', 'Portuguese', 'Rato']","['Breakfast', 'Full Bar Available', 'Brunch', ..."
12674,Midori - Penha Longa Resort,Alcabideche,4.6,246,220 € for two people (approx.),Cash and Cards accepted,['Fine Dining'],"['Japanese', 'Sushi', 'Author', 'Alcabideche']","['Full Bar Available', 'Indoor Seating', 'Luxu..."
12675,Tágide,Chiado,4.2,235,65 € for two people (approx.),Cash and Cards accepted,['Fine Dining'],"['Portuguese', 'Chiado']","['Full Bar Available', 'Lunch Menu', 'River Vi..."
12676,A Confraria - York House Lisboa Hotel,Santos,3.7,12,50 € for two people (approx.),Cash and Cards accepted,['Fine Dining'],"['Portuguese', 'Tea', 'Santos']","['Breakfast', 'Full Bar Available', 'Rooftop',..."

In [12]:
df[df['cash_cards?'] == "How do we calculate cost for two?"]

,name,neighborhood,avg_rating,#_of_ratings,avg_cost,cash_cards?,type,cuisine,more_infos
ID,,,,,,,,,
1318,Rosa Café,Linda-a-Velha,-,0,6 € for two people (approx.),How do we calculate cost for two?,['Snack Bar'],"['Cafe', 'Finger Food', 'Linda-a-Velha']","['Breakfast', 'Takeaway Available', 'Full Bar ..."
2443,Café da Mila,São João,3.0,2,8 € for two people (approx.),How do we calculate cost for two?,['Snack Bar'],"['Cafe', 'Finger Food', 'São João']","['Breakfast', 'Full Bar Available', 'Sports TV..."
3719,Cafetaria da Parada,São João,3.2,0,6 € for two people (approx.),How do we calculate cost for two?,['Snack Bar'],"['Cafe', 'Bakery', 'São João']","['Breakfast', 'Full Bar Available', 'Indoor Se..."